/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import pengu.messenger.PenguMessengerClient;
import pengu.messenger.PenguRESTClient;

/**
 * This class creates a Registration Screen.
 * 
 * @author Shivun Chinniah
 */
public class RegistrationScreen extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationScreen
     */
    public RegistrationScreen() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        repassword = new javax.swing.JPasswordField();
        unstat = new javax.swing.JLabel();
        emstat = new javax.swing.JLabel();
        psstat = new javax.swing.JLabel();
        repsstat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        loadstat = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pengu Messenger Sign-Up");
        setIconImage((new javax.swing.ImageIcon(getClass().getResource("/UI/resources/Pengu Messenger.png")).getImage()));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 438));

        jLabel2.setText("Username:");

        username.setMaximumSize(new java.awt.Dimension(22, 35));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameKeyReleased(evt);
            }
        });

        jLabel3.setText("E-mail:");

        email.setMaximumSize(new java.awt.Dimension(22, 35));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });

        jLabel4.setText("Password:");

        password.setMaximumSize(new java.awt.Dimension(22, 35));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });

        jLabel5.setText("Re-enter password:");

        repassword.setMaximumSize(new java.awt.Dimension(22, 35));
        repassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                repasswordKeyReleased(evt);
            }
        });

        unstat.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        unstat.setForeground(new java.awt.Color(106, 106, 106));
        unstat.setText("*This will be your identity");
        unstat.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        emstat.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        emstat.setForeground(new java.awt.Color(106, 106, 106));
        emstat.setText("*A varification e-mail will be sent");

        psstat.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        psstat.setForeground(new java.awt.Color(106, 106, 106));
        psstat.setText("*Remember me");

        repsstat.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        repsstat.setForeground(new java.awt.Color(106, 106, 106));
        repsstat.setText("*Re-remeber me");

        jLabel10.setText("Already have an acount?");

        login.setForeground(new java.awt.Color(0, 47, 255));
        login.setText("Log-In");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });

        signup.setText("Sign-Up");
        signup.setEnabled(false);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/resources/PenguMessenger_Signup.jpg"))); // NOI18N

        btnHelp.setText("?");
        btnHelp.setToolTipText("Sign-up Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHelp)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unstat, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(emstat))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(psstat))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(repassword, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(repsstat))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(loadstat, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jLabel6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unstat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emstat))
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psstat)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repsstat)
                    .addComponent(repassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(login)
                            .addComponent(btnHelp))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadstat, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyReleased
        // TODO add your handling code here:
        validate_username();
    }//GEN-LAST:event_usernameKeyReleased

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        String em = email.getText();
        em = em.toLowerCase();
        email.setText(em);
    }//GEN-LAST:event_emailFocusLost

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        // TODO add your handling code here:
        validate_email();
    }//GEN-LAST:event_emailKeyReleased

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:
        validate_password();
    }//GEN-LAST:event_passwordKeyReleased

    private void repasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_repasswordKeyReleased
        // TODO add your handling code here:
        validate_repassword();
    }//GEN-LAST:event_repasswordKeyReleased

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        this.signup.setEnabled(false);
        this.loadstat.setForeground(new Color(77, 77, 77));
        this.loadstat.setText("Loading...");
        this.loadstat.setIcon(new ImageIcon(getClass().getResource("/UI/resources/loader.gif")));

        new Thread(() -> {
            //time consuming algorithm.
            sendSignUp();
            
            SwingUtilities.invokeLater(() -> {
                //done
                loadstat.setIcon(null);
                loadstat.setText("");
                
                update_valid();
            });
        }).start();
        
      

    }//GEN-LAST:event_signupActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LoginScreen().setVisible(true);
    }//GEN-LAST:event_loginMouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        try {
            openWebpage(new URL("https://www.diorb.com/pengumessenger/help/#sign-up"));
        } catch (MalformedURLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnHelpActionPerformed
       
    private static boolean openWebpage(URI uri) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(uri);
                return true;
            } catch (IOException ex) {
                System.out.println(ex);
            }
        }
        return false;
    }

    private static boolean openWebpage(URL url) {
        try {
            return openWebpage(url.toURI());
        } catch (URISyntaxException ex) {
            System.out.println(ex);
        }
        return false;
    }
    
    private boolean userbool = false, emailbool = false, passbool = false, repassbool = false;


    private void update_valid() {

        if (userbool && emailbool && passbool && repassbool) {
            signup.setEnabled(true);
        } else {
            signup.setEnabled(false);
        }

    }

    private void validate_username() {
        String us = username.getText();
        if (us.contains(" ")) {
            us = us.replace(" ", "_");
            username.setText(us);
        }
        String allowed = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890_-";

        if (us.length() < 6) {
            unstat.setForeground(Color.red);
            unstat.setText("Needs to be at least 6 characters");
            userbool = false;
        } else if (us.length() > 30) {
            unstat.setForeground(Color.red);
            unstat.setText("Maximum 30 characters");
            userbool = false;
        } else if (!contains(allowed, us)) {

            unstat.setForeground(Color.red);
            unstat.setText("<html>Only Alphanumeric,<br> \"-\" and \"_\" characters</html>");
            userbool = false;
        } else if (existing_users.indexOf(us.toLowerCase()) > -1) {
            unstat.setForeground(Color.red);
            unstat.setText("Username exists");
            userbool = false;

        } else {
            unstat.setForeground(new Color(17, 109, 32));
            unstat.setText("All good!");
            userbool = true;

        }

        update_valid();
    }

    private void validate_email() {
        String em = email.getText();

        String email_pattern = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        Pattern ptn = Pattern.compile(email_pattern);
        Matcher mtch = ptn.matcher(em);


        if (existing_email.indexOf(em.toLowerCase()) > -1) {
            
            emstat.setForeground(Color.red);
            emstat.setText("E-mail address already used");
            emailbool = false;
        } else if (mtch.matches()) {
            emstat.setForeground(new Color(17, 109, 32));
            emstat.setText("Awesome!");
            emailbool = true;
        } else {
            emstat.setForeground(Color.red);
            emstat.setText("Invalid E-mail address");
            emailbool = false;
        }

        update_valid();

    }

    private void validate_password() {
        char[] pswd = password.getPassword();

        if (pswd.length < 6) {
            psstat.setForeground(Color.red);
            psstat.setText("Password too short");
            passbool = false;
        } else if (pswd.length > 64) {
            psstat.setForeground(Color.red);
            psstat.setText("Password length limmit exceeded");
            passbool = false;
        } else {
            psstat.setForeground(new Color(17, 109, 32));
            psstat.setText("Password Okay!");
            passbool = true;
        }

        update_valid();
    }

    private void validate_repassword() {
        if (new String(password.getPassword()).equals(new String(repassword.getPassword()))) {
            repsstat.setForeground(new Color(17, 109, 32));
            repsstat.setText("Let's Go!");
            repassbool = true;
        } else {
            repsstat.setForeground(Color.red);
            repsstat.setText("Passwords do not match");
            repassbool = false;
        }
        update_valid();
    }

   

    private final ArrayList existing_users = new ArrayList();
    private final ArrayList existing_email = new ArrayList();

    private static boolean contains(String allowed, String str) {
        if (str.length() == 0) {
            return false;
        } else {
            boolean stat = true;
            for (int i = 0; i <= str.length() - 1; i++) {
                stat = stat & allowed.contains(str.charAt(i) + "");
            }
            return stat;
        }
    }

    private void sendSignUp() {
        String uname = this.username.getText();
        String eml = this.email.getText();
        String pass = this.password.getText();
        
        PenguMessengerClient pmc = new PenguMessengerClient();
        try {
            pmc.Register(uname, eml, pass);
            new LoginScreen("<html>A verification email has been sent to:<br>"+eml.toLowerCase()+".</html>", new Color(78, 132, 91)).setVisible(true);
            this.dispose();
            
        } catch (PenguRESTClient.ForbiddenException ex) {
            if(ex.getForbiddenMessage().toLowerCase().contains("username")){
                existing_users.add(uname.toLowerCase());
                validate_username();
                
            }else{
                existing_email.add(eml.toLowerCase());
                validate_email();
            }
        } catch (PenguMessengerClient.ServerProblemException ex) {
            JOptionPane.showMessageDialog(this, ex.getDescription(), "Server Error.",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelp;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emstat;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loadstat;
    private javax.swing.JLabel login;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel psstat;
    private javax.swing.JPasswordField repassword;
    private javax.swing.JLabel repsstat;
    private javax.swing.JButton signup;
    private javax.swing.JLabel unstat;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
